"""
=============================================================================
MODULE 1: Data Center Thermal Model
=============================================================================
Project : GX×DX Closed-Loop Digital Twin
Author  : V Niranjana | IIT Jodhpur
Purpose : Models the thermal energy output of a 100kW modular data center.
          Computes waste heat available for recovery based on IT load,
          PUE, airflow, and ambient temperature.

Key Physics:
  - Nearly 100% of electrical energy consumed by servers becomes heat
  - Q_waste = IT_load × CPU_utilization  [kW]
  - Outlet air temp from racks: T_out = T_in + Q / (ṁ × Cp)
  - Heat available for recovery = Q_waste × recovery_efficiency
=============================================================================
"""

import numpy as np

# ---------------------------------------------------------------------------
# CONSTANTS
# ---------------------------------------------------------------------------

WATER_CP        = 4.186       # kJ/kg·K  — specific heat of water
GLYCOL_CP       = 3.500       # kJ/kg·K  — specific heat of 40% glycol-water mix
AIR_CP          = 1.006       # kJ/kg·K  — specific heat of air
AIR_DENSITY     = 1.2         # kg/m³    — air density at ~20°C
SERVER_ETA      = 0.98        # fraction — ~98% of IT power becomes heat
DEFAULT_PUE     = 1.4         # dimensionless — typical modular data center PUE
                               # PUE = Total Facility Power / IT Equipment Power
                               # 1.4 means for every 1kW compute, 1.4kW total used

# ---------------------------------------------------------------------------
# CORE CLASS
# ---------------------------------------------------------------------------

class DataCenterThermalModel:
    """
    Models a modular data center's thermal output.

    Parameters
    ----------
    it_capacity_kw : float
        Rated IT load of the data center module [kW]. Default = 100 kW.
    pue : float
        Power Usage Effectiveness. Default = 1.4
    inlet_temp_c : float
        Temperature of cooling air entering server racks [°C]. Default = 20°C.
    airflow_m3s : float
        Volumetric airflow rate through server racks [m³/s]. Default = 2.5 m³/s.
    recovery_efficiency : float
        Fraction of waste heat that can be captured by the heat exchanger loop.
        Typical range: 0.60–0.85. Default = 0.70 (conservative).
    """

    def __init__(
        self,
        it_capacity_kw     = 100.0,
        pue                = DEFAULT_PUE,
        inlet_temp_c       = 20.0,
        airflow_m3s        = 2.5,
        recovery_efficiency= 0.70
    ):
        self.it_capacity_kw      = it_capacity_kw
        self.pue                 = pue
        self.inlet_temp_c        = inlet_temp_c
        self.airflow_m3s         = airflow_m3s
        self.recovery_efficiency = recovery_efficiency

    # ------------------------------------------------------------------
    def compute(self, cpu_utilization: float) -> dict:
        """
        Main computation method. Given a CPU utilization (0.0 to 1.0),
        returns all thermal quantities for this timestep.

        Parameters
        ----------
        cpu_utilization : float
            Fraction of IT capacity in use. 0.0 = idle, 1.0 = full load.

        Returns
        -------
        dict with all computed thermal quantities.
        """

        # --- Clamp input to valid range ---
        cpu_utilization = np.clip(cpu_utilization, 0.05, 1.0)
        # Even at "idle", servers draw ~5–10% load (OS processes, standby)

        # --- Step 1: Actual IT power being consumed ---
        # At 60% CPU → 60kW of the 100kW capacity is active
        it_power_kw = self.it_capacity_kw * cpu_utilization

        # --- Step 2: Total facility power (includes cooling overhead) ---
        # PUE accounts for lights, cooling fans, UPS losses
        total_facility_power_kw = it_power_kw * self.pue

        # --- Step 3: Overhead power (non-IT: cooling fans, UPS, lighting) ---
        overhead_power_kw = total_facility_power_kw - it_power_kw

        # --- Step 4: Heat generated by servers ---
        # ~98% of IT electrical energy becomes heat (SERVER_ETA)
        # The remaining 2% is radiated as EM/RF noise — negligible but accurate
        q_server_heat_kw = it_power_kw * SERVER_ETA

        # --- Step 5: Total waste heat (servers + overhead equipment) ---
        # Overhead equipment also generates heat
        q_total_waste_kw = q_server_heat_kw + overhead_power_kw

        # --- Step 6: Outlet air temperature from server racks ---
        # Energy balance on airflow: Q = ṁ × Cp × ΔT
        # → ΔT = Q / (ṁ × Cp)
        # ṁ (mass flow) = density × volumetric flow
        mass_flow_air_kgs = AIR_DENSITY * self.airflow_m3s   # kg/s

        # ΔT across server rack [K or °C — same magnitude]
        # Convert kW → kJ/s (same unit since 1 kW = 1 kJ/s)
        delta_T_rack = q_server_heat_kw / (mass_flow_air_kgs * AIR_CP)

        # Hot air outlet temperature
        outlet_temp_c = self.inlet_temp_c + delta_T_rack

        # --- Step 7: Recoverable heat ---
        # Not all waste heat can be captured — ducts, losses, mixing
        q_recoverable_kw = q_total_waste_kw * self.recovery_efficiency

        # --- Step 8: Unrecovered heat (rejected to atmosphere) ---
        q_rejected_kw = q_total_waste_kw - q_recoverable_kw

        # --- Step 9: Carbon footprint of facility power ---
        # India grid emission factor: ~0.82 kgCO2/kWh (CEA 2023)
        # This is BEFORE our renewable integration — baseline for comparison
        INDIA_GRID_EF = 0.82   # kgCO2 per kWh
        co2_per_hour_kg = total_facility_power_kw * INDIA_GRID_EF
        # (kW × 1 hour = kWh; × emission factor = kgCO2)

        return {
            # Inputs (echoed for traceability)
            "cpu_utilization_pct"     : round(cpu_utilization * 100, 1),
            "it_capacity_kw"          : self.it_capacity_kw,
            "pue"                     : self.pue,

            # Power flows
            "it_power_kw"             : round(it_power_kw, 2),
            "overhead_power_kw"       : round(overhead_power_kw, 2),
            "total_facility_power_kw" : round(total_facility_power_kw, 2),

            # Heat quantities
            "q_server_heat_kw"        : round(q_server_heat_kw, 2),
            "q_total_waste_kw"        : round(q_total_waste_kw, 2),
            "q_recoverable_kw"        : round(q_recoverable_kw, 2),
            "q_rejected_kw"           : round(q_rejected_kw, 2),

            # Temperatures
            "inlet_temp_c"            : self.inlet_temp_c,
            "outlet_temp_c"           : round(outlet_temp_c, 2),
            "delta_T_rack_c"          : round(delta_T_rack, 2),

            # Emissions baseline
            "co2_grid_kg_per_hour"    : round(co2_per_hour_kg, 2),
        }

    # ------------------------------------------------------------------
    def simulate_day(self, cpu_profile: list) -> list:
        """
        Simulate a full 24-hour day given an hourly CPU utilization profile.

        Parameters
        ----------
        cpu_profile : list of 24 floats
            Each value is CPU utilization (0.0–1.0) for that hour.

        Returns
        -------
        List of 24 result dicts (one per hour).
        """
        if len(cpu_profile) != 24:
            raise ValueError(f"cpu_profile must have 24 values, got {len(cpu_profile)}")

        return [self.compute(cpu) for cpu in cpu_profile]


# ---------------------------------------------------------------------------
# REALISTIC CPU PROFILES (for simulation and testing)
# ---------------------------------------------------------------------------

def get_cpu_profile(profile_type: str = "office") -> list:
    """
    Returns a realistic 24-hour CPU utilization profile.

    Profile Types
    -------------
    "office"     — Business hours peak (9am–6pm)
    "cloud"      — Constant high load (cloud provider pattern)
    "night_batch"— Batch jobs run at night (2am–5am peak)
    "variable"   — Random realistic fluctuation
    """

    profiles = {
        # Typical enterprise data center
        # Low at night, builds up through morning, peaks afternoon
        "office": [
            0.15, 0.12, 0.10, 0.10, 0.12, 0.18,   # 0–5  AM: night/early morning
            0.30, 0.55, 0.72, 0.80, 0.85, 0.88,   # 6–11 AM: morning ramp-up
            0.90, 0.88, 0.85, 0.82, 0.80, 0.75,   # 12–5 PM: afternoon peak
            0.65, 0.50, 0.40, 0.30, 0.22, 0.18,   # 6–11 PM: evening decline
        ],

        # Cloud/hyperscale: always-on workloads
        "cloud": [
            0.75, 0.72, 0.70, 0.70, 0.73, 0.76,
            0.80, 0.83, 0.87, 0.90, 0.92, 0.93,
            0.95, 0.93, 0.91, 0.90, 0.89, 0.87,
            0.85, 0.83, 0.82, 0.80, 0.78, 0.76,
        ],

        # Batch processing at night
        "night_batch": [
            0.40, 0.55, 0.85, 0.90, 0.88, 0.60,
            0.30, 0.40, 0.55, 0.60, 0.65, 0.65,
            0.60, 0.62, 0.65, 0.63, 0.60, 0.55,
            0.50, 0.45, 0.42, 0.40, 0.38, 0.38,
        ],
    }

    if profile_type not in profiles:
        raise ValueError(f"Unknown profile '{profile_type}'. Choose: {list(profiles.keys())}")

    return profiles[profile_type]


# ---------------------------------------------------------------------------
# QUICK TEST — run this file directly to verify everything works
# ---------------------------------------------------------------------------

if __name__ == "__main__":

    print("=" * 60)
    print("  DATA CENTER THERMAL MODEL — QUICK TEST")
    print("=" * 60)

    dc = DataCenterThermalModel(
        it_capacity_kw      = 100.0,
        pue                 = 1.4,
        inlet_temp_c        = 20.0,
        airflow_m3s         = 2.5,
        recovery_efficiency = 0.70
    )

    # --- Single point test ---
    print("\n📊 Single Point: 80% CPU Load")
    print("-" * 40)
    result = dc.compute(cpu_utilization=0.80)
    for key, value in result.items():
        print(f"  {key:<35} {value}")

    # --- 24-hour simulation ---
    print("\n\n📅 24-Hour Simulation (Office Profile)")
    print("-" * 60)
    profile = get_cpu_profile("office")
    daily   = dc.simulate_day(profile)

    print(f"  {'Hour':<6} {'CPU%':<8} {'IT Power':>10} {'Waste Heat':>12} {'Recoverable':>13} {'Outlet °C':>10}")
    print(f"  {'-'*6:<6} {'-'*7:<8} {'-'*10:>10} {'-'*10:>12} {'-'*11:>13} {'-'*9:>10}")

    for hour, r in enumerate(daily):
        print(
            f"  {hour:02d}:00  "
            f"  {r['cpu_utilization_pct']:>5.1f}%  "
            f"  {r['it_power_kw']:>8.1f} kW  "
            f"  {r['q_total_waste_kw']:>9.1f} kW  "
            f"  {r['q_recoverable_kw']:>9.1f} kW  "
            f"  {r['outlet_temp_c']:>8.1f} °C"
        )

    # --- Daily summary ---
    total_waste    = sum(r['q_total_waste_kw'] for r in daily)
    total_recover  = sum(r['q_recoverable_kw'] for r in daily)
    total_co2base  = sum(r['co2_grid_kg_per_hour'] for r in daily)
    avg_outlet     = np.mean([r['outlet_temp_c'] for r in daily])

    print(f"\n  {'─'*55}")
    print(f"  Total waste heat (24h)     : {total_waste:>8.1f} kWh")
    print(f"  Total recoverable heat     : {total_recover:>8.1f} kWh")
    print(f"  Avg rack outlet temp       : {avg_outlet:>8.1f} °C")
    print(f"  Baseline CO₂ (grid power)  : {total_co2base:>8.1f} kg/day")
    print(f"\n  ✅ Module 1 complete — ready to pipe into heat_exchanger.py")
    
    '''
    The core insight is that a data center doesn't "consume" energy — it c
    onverts it entirely to heat. Every watt of electrical power becomes a watt of 
    thermal energy. The PUE of 1.4 means 40% extra overhead on top. The LMTD heat 
    exchanger building next  will take that 53°C outlet air and transfer it 
    into the glycol loop.
    '''